image: maven:3.5.0-jdk-8

build-master:
  stage: build
  script:
      - mvn clean install -B
    except:
      - master


build:
  stage: build
  script:
      - mvn clean install -B
    except:
      - master

